# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Progressive Web Applications HQ
description: >
  Discover what makes a great web site more great, becoming a Progressive Web
  Application, their main features and technologies. Rediscover the Web as the ultimate platform.
baseurl: "/progressive-apps-hq" # the subpath of your site, e.g. /blog
url: "http://github.io" # the base hostname & protocol for your site
collections:
  features:
    output: true
    permalink: /features/:path/
defaults:
  - scope:
      path: ""
      type: features
    values:
      layout: feature
twitter_username: mozilla
github_username:  mozilla

# Build settings
markdown: kramdown
